require "test_helper"

class BlogPostsAiControllerTest < ActionDispatch::IntegrationTest
  # A stand-in for BlogPostAiService so controller tests never touch Claude or
  # Unsplash. Both AI methods just return the canned (already-persisted) post.
  class StubAiService
    def initialize(post)
      @post = post
    end

    def create_from_prompt(*, **) = @post
    def revise_blog_post(*, **) = @post
  end

  # A stand-in whose AI methods raise — exercises the controller's rescue path
  # (handle_ai_error) so an exception becomes a generic 422 alert, not a 500.
  class RaisingAiService
    INTERNAL_MESSAGE = "secret internal failure detail"

    def create_from_prompt(*, **) = raise StandardError, INTERNAL_MESSAGE
    def revise_blog_post(*, **) = raise StandardError, INTERNAL_MESSAGE
  end

  setup { @blog_post = blog_posts(:welcome) }

  # --- ai_new --------------------------------------------------------------
  test "GET ai_new renders the prompt form for the signed-in owner" do
    sign_in users(:louis)
    with_env("ANTHROPIC_API_KEY", "sk-ant-test") do
      get ai_new_blog_posts_url
      assert_response :success
      assert_select "form[action=?]", create_with_ai_blog_posts_path
      assert_select "textarea[name=?]", "blog_post[prompt]"
    end
  end

  test "GET ai_new is blocked for signed-out visitors" do
    get ai_new_blog_posts_url
    assert_redirected_to new_user_session_url
  end

  test "GET ai_new shows a configure notice when no API key is set" do
    sign_in users(:louis)
    with_env("ANTHROPIC_API_KEY", nil) do
      get ai_new_blog_posts_url
      assert_response :success
      assert_includes response.body, "ANTHROPIC_API_KEY"
      assert_select "textarea[name=?]", "blog_post[prompt]", false,
        "the prompt form must not render without a key"
    end
  end

  # --- create_with_ai ------------------------------------------------------
  test "POST create_with_ai (stubbed service) redirects to the new post" do
    sign_in users(:louis)
    created = BlogPost.create!(
      title: "AI Generated Post",
      html_content: "<p>Generated by Claude.</p>",
      ai_generated: true,
      user: users(:louis)
    )

    with_env("ANTHROPIC_API_KEY", "sk-ant-test") do
      BlogPostAiService.stub(:new, StubAiService.new(created)) do
        post create_with_ai_blog_posts_url, params: { blog_post: { prompt: "Write about Rails" } }
      end
    end

    assert_redirected_to blog_post_url(created)
  end

  test "POST create_with_ai degrades gracefully with no API key" do
    sign_in users(:louis)
    with_env("ANTHROPIC_API_KEY", nil) do
      post create_with_ai_blog_posts_url, params: { blog_post: { prompt: "Write about Rails" } }
      assert_response :redirect
      follow_redirect!
      assert_includes response.body, "ANTHROPIC_API_KEY"
    end
  end

  test "POST create_with_ai is blocked for signed-out visitors" do
    post create_with_ai_blog_posts_url, params: { blog_post: { prompt: "Nope" } }
    assert_redirected_to new_user_session_url
  end

  # --- ai_revise / revise_with_ai ------------------------------------------
  test "GET ai_revise renders for the signed-in owner" do
    sign_in users(:louis)
    with_env("ANTHROPIC_API_KEY", "sk-ant-test") do
      get ai_revise_blog_post_url(@blog_post)
      assert_response :success
      assert_select "form[action=?]", revise_with_ai_blog_post_path(@blog_post)
    end
  end

  test "GET ai_revise is blocked for signed-out visitors" do
    get ai_revise_blog_post_url(@blog_post)
    assert_redirected_to new_user_session_url
  end

  test "PATCH revise_with_ai (stubbed service) redirects to the post" do
    sign_in users(:louis)
    with_env("ANTHROPIC_API_KEY", "sk-ant-test") do
      BlogPostAiService.stub(:new, StubAiService.new(@blog_post)) do
        patch revise_with_ai_blog_post_url(@blog_post),
          params: { blog_post: { prompt: "Make it punchier" } }
      end
    end

    assert_redirected_to blog_post_url(@blog_post)
  end

  # --- AI unhappy paths ----------------------------------------------------
  test "POST create_with_ai re-renders ai_new with 422 when the AI result is invalid" do
    sign_in users(:louis)
    invalid = BlogPost.new(title: "", user: users(:louis)) # unpersisted, title missing
    invalid.valid? # populate errors so the failure flash has content

    with_env("ANTHROPIC_API_KEY", "sk-ant-test") do
      BlogPostAiService.stub(:new, StubAiService.new(invalid)) do
        post create_with_ai_blog_posts_url, params: { blog_post: { prompt: "Write about Rails" } }
      end
    end

    assert_response :unprocessable_entity
    assert_select "form[action=?]", create_with_ai_blog_posts_path
    # The apostrophe in the flash is HTML-escaped, so match an apostrophe-free fragment.
    assert_includes response.body, "The AI response"
  end

  test "PATCH revise_with_ai re-renders ai_revise with 422 when the AI result is invalid" do
    sign_in users(:louis)
    invalid = BlogPost.create!( # persisted (so the form path resolves) but carrying an error
      title: "Persisted But Invalid",
      html_content: "<p>x</p>",
      user: users(:louis)
    )
    invalid.errors.add(:base, "AI revision rejected")

    with_env("ANTHROPIC_API_KEY", "sk-ant-test") do
      BlogPostAiService.stub(:new, StubAiService.new(invalid)) do
        patch revise_with_ai_blog_post_url(@blog_post),
          params: { blog_post: { prompt: "Make it punchier" } }
      end
    end

    assert_response :unprocessable_entity
    assert_select "form[action=?]", revise_with_ai_blog_post_path(invalid)
    # The apostrophe in the flash is HTML-escaped, so match an apostrophe-free fragment.
    assert_includes response.body, "The AI revision"
  end

  test "POST create_with_ai renders a generic 422 alert without leaking a raised error" do
    sign_in users(:louis)
    with_env("ANTHROPIC_API_KEY", "sk-ant-test") do
      BlogPostAiService.stub(:new, RaisingAiService.new) do
        post create_with_ai_blog_posts_url, params: { blog_post: { prompt: "Write about Rails" } }
      end
    end

    assert_response :unprocessable_entity
    assert_includes response.body, "The AI encountered an error"
    assert_not_includes response.body, RaisingAiService::INTERNAL_MESSAGE,
      "the raw exception message must not leak to the user"
  end

  test "PATCH revise_with_ai renders a generic 422 alert without leaking a raised error" do
    sign_in users(:louis)
    with_env("ANTHROPIC_API_KEY", "sk-ant-test") do
      BlogPostAiService.stub(:new, RaisingAiService.new) do
        patch revise_with_ai_blog_post_url(@blog_post), params: { blog_post: { prompt: "x" } }
      end
    end

    assert_response :unprocessable_entity
    assert_includes response.body, "The AI encountered an error"
    assert_not_includes response.body, RaisingAiService::INTERNAL_MESSAGE,
      "the raw exception message must not leak to the user"
  end
end
