require "test_helper"

class BlogPostsAiControllerTest < ActionDispatch::IntegrationTest
  # A stand-in for BlogPostAiService so controller tests never touch Claude or
  # Unsplash. Both AI methods just return the canned (already-persisted) post.
  class StubAiService
    def initialize(post)
      @post = post
    end

    def create_from_prompt(*, **) = @post
    def revise_blog_post(*, **) = @post
  end

  setup { @blog_post = blog_posts(:welcome) }

  # --- ai_new --------------------------------------------------------------
  test "GET ai_new renders the prompt form for the signed-in owner" do
    sign_in users(:louis)
    with_env("ANTHROPIC_API_KEY", "sk-ant-test") do
      get ai_new_blog_posts_url
      assert_response :success
      assert_select "form[action=?]", create_with_ai_blog_posts_path
      assert_select "textarea[name=?]", "blog_post[prompt]"
    end
  end

  test "GET ai_new is blocked for signed-out visitors" do
    get ai_new_blog_posts_url
    assert_redirected_to new_user_session_url
  end

  test "GET ai_new shows a configure notice when no API key is set" do
    sign_in users(:louis)
    with_env("ANTHROPIC_API_KEY", nil) do
      get ai_new_blog_posts_url
      assert_response :success
      assert_includes response.body, "ANTHROPIC_API_KEY"
      assert_select "textarea[name=?]", "blog_post[prompt]", false,
        "the prompt form must not render without a key"
    end
  end

  # --- create_with_ai ------------------------------------------------------
  test "POST create_with_ai (stubbed service) redirects to the new post" do
    sign_in users(:louis)
    created = BlogPost.create!(
      title: "AI Generated Post",
      html_content: "<p>Generated by Claude.</p>",
      ai_generated: true,
      user: users(:louis)
    )

    with_env("ANTHROPIC_API_KEY", "sk-ant-test") do
      BlogPostAiService.stub(:new, StubAiService.new(created)) do
        post create_with_ai_blog_posts_url, params: { blog_post: { prompt: "Write about Rails" } }
      end
    end

    assert_redirected_to blog_post_url(created)
  end

  test "POST create_with_ai degrades gracefully with no API key" do
    sign_in users(:louis)
    with_env("ANTHROPIC_API_KEY", nil) do
      post create_with_ai_blog_posts_url, params: { blog_post: { prompt: "Write about Rails" } }
      assert_response :redirect
      follow_redirect!
      assert_includes response.body, "ANTHROPIC_API_KEY"
    end
  end

  test "POST create_with_ai is blocked for signed-out visitors" do
    post create_with_ai_blog_posts_url, params: { blog_post: { prompt: "Nope" } }
    assert_redirected_to new_user_session_url
  end

  # --- ai_revise / revise_with_ai ------------------------------------------
  test "GET ai_revise renders for the signed-in owner" do
    sign_in users(:louis)
    with_env("ANTHROPIC_API_KEY", "sk-ant-test") do
      get ai_revise_blog_post_url(@blog_post)
      assert_response :success
      assert_select "form[action=?]", revise_with_ai_blog_post_path(@blog_post)
    end
  end

  test "GET ai_revise is blocked for signed-out visitors" do
    get ai_revise_blog_post_url(@blog_post)
    assert_redirected_to new_user_session_url
  end

  test "PATCH revise_with_ai (stubbed service) redirects to the post" do
    sign_in users(:louis)
    with_env("ANTHROPIC_API_KEY", "sk-ant-test") do
      BlogPostAiService.stub(:new, StubAiService.new(@blog_post)) do
        patch revise_with_ai_blog_post_url(@blog_post),
          params: { blog_post: { prompt: "Make it punchier" } }
      end
    end

    assert_redirected_to blog_post_url(@blog_post)
  end
end
